---
label: Product
hide_body: false
fields:
- name: product
  type: text
  config:
    required: false
  label: Product
- name: price
  type: number
  label: Price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
pages:
- src/products/Pinpointer.md
